### ISSUE TITLE
关于cookie过期问题

### ISSUE THREAD

**Issue by rty813** [hwding/AeolosXDUWidget#2]
登陆以后 cookie一段时间就过期了 莫非要每隔一段时间就输入一次验证码登陆一次吗？我是西工大的学生，也想做一个，但是cookie这个问题一直没有解决，

**Comment by rty813** [comment]
是不是你把数据获取放在了服务器上面，你这个工程里面怎么没有看到模拟登录，爬虫的代码？

**Comment by hwding** [comment]
- Cookie的确会过期，这个问题挺恼人的，过期之后有验证码的话只能通过再输入验证码登录：（。  
- 你可以看看你们学校的系统用手机登录时的页面会不会有验证码，如果没有的话可以用那个网址登录。  
- 另外数据获取使用的这个库[libXDUQuery](https://github.com/hwding/libXDUQuery)，有将近一年没有用过了，学校系统在这个期间有变动，可能部分已经不能用了。

**Comment by hwding** [comment]
- 做一个服务器是最好的，但是这个库是直接去解析的，所以会有很多问题，比如耗流量、速度慢、不稳定等等，当时只是做着玩所以没考虑这方面的东西。
- 我的会话是否过期的检查，是先去请求需要解析的结果页面，然后根据返回的特征看看会话是不是还有效，如果过期了就用存着的账号信息重新登录，再解析结果页面，如果没有验证码这个重登陆的过程可以做成对用户透明的，然是如果有验证码的话就很麻烦了，你还得让用户输入验证码：（。

**Comment by rty813** [comment]
哎，看起来如果直接爬取我们学校的门户网站 实用性还是不大，我决定爬取我们学校其他的网站，不用验证码的。另外，可以机器学习，来识别验证码，不过我还不会。。。。你是研究生吗？

**Comment by hwding** [comment]
- 唔， 你想做好的话可以考虑去向学校申请下接口：P。
- 验证码识别的库我用过，对我我们学校的很普通的验证码基本不顶用，你说的机器学习的方法我也不会，所以没试过。
- 你可以尝试去爬论坛之类的。
- 现在大二。

**Comment by rty813** [comment]
哇 我也大二，论坛啥的没啥实际的用处，

**Comment by hwding** [comment]
是的，要拿学校的系统的话不直接拿接口很难做的，而且一般学校这种东西都不会对外提供接口的...

**Comment by rty813** [comment]
是啊，我也是做着玩，哈哈 那我就把这个问题关闭了吧

**Comment by hwding** [comment]
行，以后多交流啊：）。

**Comment by rty813** [comment]
ok~
